In [1]:
import pandas as pd
import numpy as np
import matplotlib
import ast
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings('ignore')

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

#폰트 설정(없으면 영문으로 나옴)
try:
    font_path = [f for f in fm.findSystemFonts() if 'NanumGothic' in f or 'Malgun' in f or 'AppleGothic' in f]
    if font_path:
        plt.rcParams['font.family'] = fm.FontProperties(fname=font_path[0]).get_name()
    else:
        plt.rcParams['font.family'] = 'DejaVu Sans'
except:
    plt.rcParams['font.family'] = 'DejaVu Sans'

plt.rcParams['axes.unicode_minus'] = False

In [2]:
df = pd.read_csv('./funnel_instance_analysis.csv')

In [3]:
df.shape

(76277, 34)

In [4]:
df.head()

,customer_id,offer_id,t_received,offer_type,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,is_viewed,is_completed,completed_without_prior_view,gap_view_to_complete,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,gender,age_group,income_group,join_year,join_month,join_cohort
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,576,discount,1,7.0,744.0,NaN,NaN,NaN,NaN,576.0,576.0,1.0,0.0,NaN,0.0,False,True,True,NaN,2.0,10.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,336,informational,1,4.0,432.0,372.0,372.0,1.0,0.0,NaN,NaN,NaN,NaN,36.0,NaN,True,False,False,NaN,0.0,0.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,168,informational,1,3.0,240.0,192.0,192.0,1.0,0.0,NaN,NaN,NaN,NaN,24.0,NaN,True,False,False,NaN,0.0,0.0,0.0,1.0,1.0,1.0,3.0,M,30대,5-7.5만,2017,4,2017-04
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,408,bogo,1,5.0,528.0,456.0,456.0,1.0,0.0,414.0,414.0,1.0,0.0,48.0,6.0,True,True,True,NaN,5.0,5.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,504,discount,1,10.0,744.0,540.0,540.0,1.0,0.0,528.0,528.0,1.0,0.0,36.0,24.0,True,True,True,NaN,2.0,10.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76277 entries, 0 to 76276
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   76277 non-null  str
 1   offer_id                      76277 non-null  str
 2   t_received                    76277 non-null  int64
 3   offer_type                    76277 non-null  str
 4   instance_id                   76277 non-null  int64
 5   duration                      76277 non-null  float64
 6   t_expire                      76277 non-null  float64
 7   t_viewed                      56567 non-null  float64
 8   last_viewed                   56567 non-null  float64
 9   view_count                    56567 non-null  float64
 10  view_ambiguous                56567 non-null  float64
 11  t_completed                   33101 non-null  float64
 12  last_completed                33101 non-null  float64
 13  complete_count                33101 non-null  float64
 14  comp_ambiguous                33101 non-null  float64
 15  gap_to_view                   56567 non-null  float64
 16  gap_to_complete               33101 non-null  float64
 17  is_viewed                     76277 non-null  bool
 18  is_completed                  76277 non-null  bool
 19  completed_without_prior_view  76277 non-null  bool
 20  gap_view_to_complete          20548 non-null  float64
 21  reward                        76277 non-null  float64
 22  difficulty                    76277 non-null  float64
 23  ch_web                        76277 non-null  float64
 24  ch_email                      76277 non-null  float64
 25  ch_mobile                     76277 non-null  float64
 26  ch_social                     76277 non-null  float64
 27  channel_count                 76277 non-null  float64
 28  gender                        76277 non-null  str
 29  age_group                     76277 non-null  str
 30  income_group                  76277 non-null  str
 31  join_year                     76277 non-null  int64
 32  join_month                    76277 non-null  int64
 33  join_cohort                   76277 non-null  str
dtypes: bool(3), float64(20), int64(4), str(7)
memory usage: 18.3 MB

In [6]:
df.describe()

,t_received,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,gap_view_to_complete,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,join_year,join_month
count,76277.000000,76277.000000,76277.000000,76277.000000,56567.000000,56567.000000,56567.0,56567.000000,33101.000000,33101.000000,33101.000000,33101.000000,56567.000000,33101.000000,20548.000000,76277.000000,76277.000000,76277.000000,76277.0,76277.000000,76277.000000,76277.000000,76277.000000,76277.000000
mean,332.579519,1.188012,6.503704,488.668406,353.750314,353.750314,1.0,0.041349,399.275430,399.413915,1.014441,0.040120,24.365620,61.174949,51.023360,4.201607,7.707723,0.799730,1.0,0.899472,0.598909,3.298111,2016.636522,6.678920
std,196.489548,0.436315,2.201544,203.330265,199.139007,199.139007,0.0,0.199098,192.748223,192.831514,0.119553,0.196243,28.453521,50.622756,42.742651,3.398888,5.538203,0.400205,0.0,0.300705,0.490123,0.640549,1.178704,3.489456
min,0.000000,1.000000,3.000000,72.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,2.000000,2013.000000,1.000000
25%,168.000000,1.000000,5.000000,336.000000,180.000000,180.000000,1.0,0.000000,234.000000,234.000000,1.000000,0.000000,6.000000,18.000000,18.000000,2.000000,5.000000,1.000000,1.0,1.000000,0.000000,3.000000,2016.000000,4.000000
50%,408.000000,1.000000,7.000000,528.000000,408.000000,408.000000,1.0,0.000000,432.000000,432.000000,1.000000,0.000000,12.000000,48.000000,36.000000,5.000000,10.000000,1.000000,1.0,1.000000,1.000000,3.000000,2017.000000,7.000000
75%,504.000000,1.000000,7.000000,672.000000,516.000000,516.000000,1.0,0.000000,558.000000,558.000000,1.000000,0.000000,36.000000,90.000000,72.000000,5.000000,10.000000,1.000000,1.0,1.000000,1.000000,4.000000,2017.000000,10.000000
max,576.000000,5.000000,10.000000,816.000000,714.000000,714.000000,1.0,1.000000,714.000000,714.000000,3.000000,1.000000,240.000000,240.000000,240.000000,10.000000,20.000000,1.000000,1.0,1.000000,1.000000,4.000000,2018.000000,12.000000

In [7]:
df.columns

Index(['customer_id', 'offer_id', 't_received', 'offer_type', 'instance_id',
       'duration', 't_expire', 't_viewed', 'last_viewed', 'view_count',
       'view_ambiguous', 't_completed', 'last_completed', 'complete_count',
       'comp_ambiguous', 'gap_to_view', 'gap_to_complete', 'is_viewed',
       'is_completed', 'completed_without_prior_view', 'gap_view_to_complete',
       'reward', 'difficulty', 'ch_web', 'ch_email', 'ch_mobile', 'ch_social',
       'channel_count', 'gender', 'age_group', 'income_group', 'join_year',
       'join_month', 'join_cohort'],
      dtype='str')

In [8]:
seg = (
    df.groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed_rate=('is_viewed', 'mean'),
        completed_rate=('is_completed', 'mean')
    ).reset_index()
)

seg.head()

  gender age_group income_group    n  viewed_rate  completed_rate
0      F       20대       5-7.5만  973     0.683453        0.540596
1      F       20대        5만 미만  806     0.699752        0.468983
2      F       20대      7.5-10만   14     0.785714        0.857143
3      F    20대 미만       5-7.5만  127     0.669291        0.448819
4      F    20대 미만        5만 미만   76     0.750000        0.342105

In [9]:
seg_sorted = seg.sort_values('completed_rate', ascending=False)
seg_sorted.head(10)

   gender age_group income_group    n  viewed_rate  completed_rate
5       F       30대       10만 이상    4     1.000000        1.000000
2       F       20대      7.5-10만   14     0.785714        0.857143
26      M       30대       10만 이상    4     1.000000        0.750000
44      O       30대       5-7.5만   39     0.769231        0.717949
57      O    60대 이상      7.5-10만   73     1.000000        0.671233
51      O       50대       10만 이상    3     1.000000        0.666667
8       F       30대      7.5-10만  208     0.947115        0.658654
50      O       40대      7.5-10만   65     0.938462        0.646154
52      O       50대       5-7.5만   90     0.911111        0.644444
38      M    60대 이상       10만 이상  929     0.630786        0.635091

In [10]:
seg_filtered = seg[seg['n']>=100]
seg_filtered.sort_values('completed_rate', ascending=False).head(10)

   gender age_group income_group     n  viewed_rate  completed_rate
8       F       30대      7.5-10만   208     0.947115        0.658654
38      M    60대 이상       10만 이상   929     0.630786        0.635091
13      F       50대       10만 이상  1113     0.640611        0.619048
17      F    60대 이상       10만 이상  2039     0.648847        0.608632
20      F    60대 이상      7.5-10만  4577     0.721870        0.605418
9       F       40대       10만 이상   158     0.715190        0.601266
16      F       50대      7.5-10만  2738     0.735208        0.601169
34      M       50대       10만 이상   588     0.637755        0.598639
12      F       40대      7.5-10만   889     0.870641        0.592801
41      M    60대 이상      7.5-10만  3320     0.790361        0.588855

# complete_given_view를 보는 이유
 - 단순 completed_rate는 '받은 전체 오퍼 중 완료 비율'이므로,
    - 오퍼를 실제로 본 뒤 행동한 것인지까지는 구분하지 못한다.
    - 이번 분석에서는 퍼널 구조(received → viewed → completed)를 반영해,
    - '오퍼를 본 사람들 중 실제 완료로 이어진 비율'을 따로 확인하고자 한다.
- 이를 통해
   1) 오퍼를 봤을 때 구매로 잘 이어지는 고객층
   2) 오퍼를 보지 않았는데도 완료되는 고객층을 구분해 해석할 수 있다.
- 전자는 어떤 오퍼가 효과적인지 추가 분석 대상으로, 후자는 프로모션 효율 재검토 대상으로 볼 수 있다.

In [11]:
seg = (
    df
    .groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed_rate=('is_viewed', 'mean'),
        completed_rate=('is_completed', 'mean'),
        completed_without_view_rate=('completed_without_prior_view', 'mean')
    )
    .reset_index()
)

seg['complete_given_view'] = np.where(
    seg['viewed_rate'] > 0,
    seg['completed_rate'] / seg['viewed_rate'],
    np.nan
)

seg.head()

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
1,F,20대,5만 미만,806,0.699752,0.468983,0.162531,0.670213
2,F,20대,7.5-10만,14,0.785714,0.857143,0.428571,1.090909
3,F,20대 미만,5-7.5만,127,0.669291,0.448819,0.196850,0.670588
4,F,20대 미만,5만 미만,76,0.750000,0.342105,0.144737,0.456140

In [12]:
seg[seg['n'] >= 100].sort_values('complete_given_view', ascending=False).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
38,M,60대 이상,10만 이상,929,0.630786,0.635091,0.258342,1.006826
13,F,50대,10만 이상,1113,0.640611,0.619048,0.242588,0.966339
34,M,50대,10만 이상,588,0.637755,0.598639,0.241497,0.938667
17,F,60대 이상,10만 이상,2039,0.648847,0.608632,0.243747,0.938020
9,F,40대,10만 이상,158,0.715190,0.601266,0.196203,0.840708
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
6,F,30대,5-7.5만,1140,0.722807,0.552632,0.192105,0.764563
41,M,60대 이상,7.5-10만,3320,0.790361,0.588855,0.180422,0.745046

In [13]:
seg[seg['n'] >= 100].sort_values('completed_without_view_rate', ascending=False).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
38,M,60대 이상,10만 이상,929,0.630786,0.635091,0.258342,1.006826
17,F,60대 이상,10만 이상,2039,0.648847,0.608632,0.243747,0.938020
13,F,50대,10만 이상,1113,0.640611,0.619048,0.242588,0.966339
34,M,50대,10만 이상,588,0.637755,0.598639,0.241497,0.938667
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685
3,F,20대 미만,5-7.5만,127,0.669291,0.448819,0.196850,0.670588
9,F,40대,10만 이상,158,0.715190,0.601266,0.196203,0.840708
6,F,30대,5-7.5만,1140,0.722807,0.552632,0.192105,0.764563

In [14]:
seg['segment_share'] = seg['n'] / seg['n'].sum()
seg.head()

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view,segment_share
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977,0.012756
1,F,20대,5만 미만,806,0.699752,0.468983,0.162531,0.670213,0.010567
2,F,20대,7.5-10만,14,0.785714,0.857143,0.428571,1.090909,0.000184
3,F,20대 미만,5-7.5만,127,0.669291,0.448819,0.196850,0.670588,0.001665
4,F,20대 미만,5만 미만,76,0.750000,0.342105,0.144737,0.456140,0.000996

In [15]:
seg[seg['n'] >= 100].sort_values(
    ['complete_given_view', 'n'],
    ascending=[False, False]
).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view,segment_share
38,M,60대 이상,10만 이상,929,0.630786,0.635091,0.258342,1.006826,0.012179
13,F,50대,10만 이상,1113,0.640611,0.619048,0.242588,0.966339,0.014592
34,M,50대,10만 이상,588,0.637755,0.598639,0.241497,0.938667,0.007709
17,F,60대 이상,10만 이상,2039,0.648847,0.608632,0.243747,0.938020,0.026732
9,F,40대,10만 이상,158,0.715190,0.601266,0.196203,0.840708,0.002071
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680,0.060005
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685,0.035895
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977,0.012756
6,F,30대,5-7.5만,1140,0.722807,0.552632,0.192105,0.764563,0.014946
41,M,60대 이상,7.5-10만,3320,0.790361,0.588855,0.180422,0.745046,0.043526

In [16]:
seg.sort_values('n', ascending=False).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view,segment_share
58,Unknown,누락,누락,9776,0.790098,0.112623,0.017185,0.142543,0.128164
39,M,60대 이상,5-7.5만,5948,0.765131,0.439307,0.115669,0.574160,0.077979
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680,0.060005
18,F,60대 이상,5-7.5만,4269,0.799953,0.546030,0.144062,0.682577,0.055967
35,M,50대,5-7.5만,3761,0.779314,0.461845,0.120978,0.592631,0.049307
40,M,60대 이상,5만 미만,3334,0.664967,0.307439,0.096281,0.462336,0.043709
41,M,60대 이상,7.5-10만,3320,0.790361,0.588855,0.180422,0.745046,0.043526
31,M,40대,5-7.5만,3166,0.774479,0.432407,0.098231,0.558320,0.041507
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685,0.035895
14,F,50대,5-7.5만,2390,0.785356,0.558159,0.156904,0.710709,0.031333

In [17]:
seg = (
    df
    .groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum'),
        viewed_and_completed=(
            'is_completed',
            lambda x: ((x == True) & (df.loc[x.index, 'is_viewed'] == True)).sum()
        ),
        completed_without_view=('completed_without_prior_view', 'sum')
    )
    .reset_index()
)

In [18]:
seg['complete_given_view'] = seg['viewed_and_completed'] / seg['viewed']
seg[seg['n'] >= 100].sort_values(
    ['complete_given_view', 'n'],
    ascending=[False, False]
).head(10)

,gender,age_group,income_group,n,viewed,completed,viewed_and_completed,completed_without_view,complete_given_view
38,M,60대 이상,10만 이상,929,586,590,421,240,0.718430
13,F,50대,10만 이상,1113,713,689,502,270,0.704067
17,F,60대 이상,10만 이상,2039,1323,1241,917,497,0.693122
34,M,50대,10만 이상,588,375,352,253,142,0.674667
20,F,60대 이상,7.5-10만,4577,3304,2771,2222,933,0.672518
8,F,30대,7.5-10만,208,197,137,130,15,0.659898
9,F,40대,10만 이상,158,113,95,74,31,0.654867
16,F,50대,7.5-10만,2738,2013,1646,1308,553,0.649776
41,M,60대 이상,7.5-10만,3320,2624,1955,1624,599,0.618902
37,M,50대,7.5-10만,2240,1765,1290,1092,367,0.618697

In [19]:
seg['completed_without_view_ratio'] = seg['completed_without_view'] / seg['completed']

In [20]:
seg[seg['n'] >= 100].sort_values(
    ['completed_without_view_ratio'],
    ascending=False
).head(10)

,gender,age_group,income_group,n,viewed,completed,viewed_and_completed,completed_without_view,complete_given_view,completed_without_view_ratio
3,F,20대 미만,5-7.5만,127,85,57,46,25,0.541176,0.438596
38,M,60대 이상,10만 이상,929,586,590,421,240,0.718430,0.406780
34,M,50대,10만 이상,588,375,352,253,142,0.674667,0.403409
17,F,60대 이상,10만 이상,2039,1323,1241,917,497,0.693122,0.400483
13,F,50대,10만 이상,1113,713,689,502,270,0.704067,0.391872
0,F,20대,5-7.5만,973,665,526,400,205,0.601504,0.389734
15,F,50대,5만 미만,809,539,380,289,145,0.536178,0.381579
6,F,30대,5-7.5만,1140,824,630,508,219,0.616505,0.347619
1,F,20대,5만 미만,806,564,378,310,131,0.549645,0.346561
19,F,60대 이상,5만 미만,1574,1077,719,554,244,0.514392,0.339360

#### 고객 유형 별 오퍼 분석 1 
- 고연령·고소득 세그먼트는 오퍼 노출 시 높은 전환율을 보이는 동시에, 오퍼 없이도 구매가 활발하게 발생하는 특성을 보인다. 이는 해당 집단이 가격 인센티브보다는 브랜드 충성도 및 소비 여력에 기반해 구매하는 경향이 있음을 시사한다. 
> 따라서 단순 할인 중심의 프로모션보다는 프리미엄 경험 및 리워드 중심 전략이 더 효과적일 가능성이 있다.

## 고연령 고소득 세그먼트에겐 어떤 오퍼?

In [21]:
df['is_viewed_before_completed'] = (
    (df['is_viewed'] == True) &
    (df['is_completed'] == True) &
    (df['t_viewed'] < df['t_completed']))

In [22]:
target_df = df[
    (df['age_group'].isin(['50대', '60대 이상'])) &
    (df['income_group'].isin(['7.5-10만', '10만 이상']))
].copy()

print(target_df.shape)
display(target_df.head())

(17740, 35)

,customer_id,offer_id,t_received,offer_type,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,is_viewed,is_completed,completed_without_prior_view,gap_view_to_complete,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,gender,age_group,income_group,join_year,join_month,join_cohort,is_viewed_before_completed
12,0020c2b971eb4e9188eac86d93036a77,4d5c57ea9a6940dd891ad53e9dbe8da0,408,bogo,1,5.0,528.0,426.0,426.0,1.0,0.0,510.0,510.0,1.0,0.0,18.0,102.0,True,True,False,84.0,10.0,10.0,1.0,1.0,1.0,1.0,4.0,F,50대,7.5-10만,2016,3,2016-03,True
13,0020c2b971eb4e9188eac86d93036a77,5a8bc65990b245e5a138643cd4eb9837,504,informational,1,3.0,576.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,NaN,0.0,0.0,0.0,1.0,1.0,1.0,3.0,F,50대,7.5-10만,2016,3,2016-03,False
14,0020c2b971eb4e9188eac86d93036a77,ae264e3637204a6fb9bb56bc8210ddfd,168,bogo,1,7.0,336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,NaN,10.0,10.0,0.0,1.0,1.0,1.0,3.0,F,50대,7.5-10만,2016,3,2016-03,False
15,0020c2b971eb4e9188eac86d93036a77,fafdcd668e3743c1bb461111dcafc2a4,0,discount,1,10.0,240.0,12.0,12.0,1.0,0.0,54.0,54.0,1.0,0.0,12.0,54.0,True,True,False,42.0,2.0,10.0,1.0,1.0,1.0,1.0,4.0,F,50대,7.5-10만,2016,3,2016-03,True
16,0020c2b971eb4e9188eac86d93036a77,fafdcd668e3743c1bb461111dcafc2a4,336,discount,2,10.0,576.0,NaN,NaN,NaN,NaN,510.0,510.0,1.0,0.0,NaN,174.0,False,True,True,NaN,2.0,10.0,1.0,1.0,1.0,1.0,4.0,F,50대,7.5-10만,2016,3,2016-03,False

In [23]:
offer_seg = (
    target_df.groupby('offer_type').agg(
        n = ('customer_id', 'count'),
        viewed = ('is_viewed', 'sum'),
        completed = ('is_completed', 'sum'),
        viewed_then_completed = (
            'is_viewed_before_completed', 'sum')
    ).reset_index()
)
offer_seg

      offer_type     n  viewed  completed  viewed_then_completed
0           bogo  7043    5654       5150                   3022
1       discount  7117    5129       5495                   3095
2  informational  3580    2109          0                      0

In [ ]:
df['is_valid_conversion'] = (
    (df['is_viewed'] == True) &
    (df['is_completed'] == True) &
    (df['t_viewed'] < df['t_completed'])
)       #보고 완료

df['is_view_only_dropout'] = (
    (df['is_viewed'] == True) &
    (df['is_completed'] == False)
)       #보고 미완료

df['is_completed_without_view'] = (
    (df['is_completed'] == True) &
    (df['is_viewed'] == False)
)       #안보고 완료

In [31]:
seg = (
    df.groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum'),
        valid_conversion=('is_valid_conversion', 'sum'),
        completed_without_view=('is_completed_without_view', 'sum'),
        view_only_dropout=('is_view_only_dropout', 'sum')
    )
    .reset_index()
)

seg['view_rate'] = seg['viewed'] / seg['n']
seg['valid_conversion_rate_per_received'] = seg['valid_conversion'] / seg['n']
seg['valid_conversion_rate_per_viewed'] = seg['valid_conversion'] / seg['viewed']
seg['completed_without_view_ratio'] = seg['completed_without_view'] / seg['completed']
seg['dropout_after_view_ratio'] = seg['view_only_dropout'] / seg['viewed']

seg.sort_values('valid_conversion', ascending=False).head(10)

,gender,age_group,income_group,n,viewed,completed,valid_conversion,completed_without_view,view_only_dropout,view_rate,valid_conversion_rate_per_received,valid_conversion_rate_per_viewed,completed_without_view_ratio,dropout_after_view_ratio
39,M,60대 이상,5-7.5만,5948,4551,2613,1732,363,2301,0.765131,0.291190,0.380576,0.138921,0.505603
20,F,60대 이상,7.5-10만,4577,3304,2771,1597,549,1082,0.721870,0.348919,0.483354,0.198123,0.327482
18,F,60대 이상,5-7.5만,4269,3415,2331,1498,314,1398,0.799953,0.350902,0.438653,0.134706,0.409370
41,M,60대 이상,7.5-10만,3320,2624,1955,1200,331,1000,0.790361,0.361446,0.457317,0.169309,0.381098
35,M,50대,5-7.5만,3761,2931,1737,1137,234,1428,0.779314,0.302313,0.387922,0.134715,0.487206
16,F,50대,7.5-10만,2738,2013,1646,958,338,705,0.735208,0.349890,0.475907,0.205346,0.350224
31,M,40대,5-7.5만,3166,2452,1369,930,155,1238,0.774479,0.293746,0.379282,0.113221,0.504894
58,Unknown,누락,누락,9776,7724,1101,889,116,6739,0.790098,0.090937,0.115096,0.105359,0.872475
14,F,50대,5-7.5만,2390,1877,1334,818,211,754,0.785356,0.342259,0.435802,0.158171,0.401705
37,M,50대,7.5-10만,2240,1765,1290,806,198,673,0.787946,0.359821,0.456657,0.153488,0.381303

In [27]:
target_df = df[
    (df['age_group'].isin(['50대', '60대 이상'])) &
    (df['income_group'].isin(['7.5-10만', '10만 이상']))
].copy()

offer_seg = (
    target_df.groupby('offer_type')
    .agg(
        n=('customer_id', 'count'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum'),
        valid_conversion=('is_valid_conversion', 'sum'),
        completed_without_view=('is_completed_without_view', 'sum')
    )
    .reset_index()
)

offer_seg['view_rate'] = offer_seg['viewed'] / offer_seg['n']
offer_seg['valid_conversion_rate_per_received'] = offer_seg['valid_conversion'] / offer_seg['n']
offer_seg['valid_conversion_rate_per_viewed'] = offer_seg['valid_conversion'] / offer_seg['viewed']
offer_seg['completed_without_view_ratio'] = offer_seg['completed_without_view'] / offer_seg['completed']
offer_seg

,offer_type,n,viewed,completed,valid_conversion,completed_without_view,view_rate,valid_conversion_rate_per_received,valid_conversion_rate_per_viewed,completed_without_view_ratio
0,bogo,7043,5654,5150,3022,886,0.802783,0.429079,0.534489,0.172039
1,discount,7117,5129,5495,3095,1309,0.720669,0.434874,0.603431,0.238217
2,informational,3580,2109,0,0,0,0.589106,0.000000,0.000000,NaN

In [35]:
# -----------------------------------
# 4) 연령대 + 성별 조합별 오퍼타입 성과 비교
# -----------------------------------

age_gender_offer_seg = (
    df.groupby(['age_group', 'gender', 'offer_type'])
    .agg(
        n=('customer_id', 'count'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum'),
        valid_conversion=('is_valid_conversion', 'sum'),
        completed_without_view=('is_completed_without_view', 'sum'),
        view_only_dropout=('is_view_only_dropout', 'sum')
    )
    .reset_index()
)

# 비율 계산
age_gender_offer_seg['view_rate'] = age_gender_offer_seg['viewed'] / age_gender_offer_seg['n']
age_gender_offer_seg['valid_conversion_rate_per_received'] = (
    age_gender_offer_seg['valid_conversion'] / age_gender_offer_seg['n']
)
age_gender_offer_seg['valid_conversion_rate_per_viewed'] = (
    age_gender_offer_seg['valid_conversion'] / age_gender_offer_seg['viewed']
)
age_gender_offer_seg['completed_without_view_ratio'] = (
    age_gender_offer_seg['completed_without_view'] / age_gender_offer_seg['completed']
)
age_gender_offer_seg['dropout_after_view_ratio'] = (
    age_gender_offer_seg['view_only_dropout'] / age_gender_offer_seg['viewed']
)

age_gender_offer_seg

,age_group,gender,offer_type,n,viewed,completed,valid_conversion,completed_without_view,view_only_dropout,view_rate,valid_conversion_rate_per_received,valid_conversion_rate_per_viewed,completed_without_view_ratio,dropout_after_view_ratio
0,20대,F,bogo,736,592,452,247,78,218,0.804348,0.335598,0.417230,0.172566,0.368243
1,20대,F,discount,701,443,464,250,119,98,0.631954,0.356633,0.564334,0.256466,0.221219
2,20대,F,informational,356,205,0,0,0,205,0.575843,0.000000,0.000000,NaN,1.000000
3,20대,M,bogo,1687,1377,582,346,104,899,0.816242,0.205098,0.251271,0.178694,0.652869
4,20대,M,discount,1816,1046,826,534,183,403,0.575991,0.294053,0.510516,0.221550,0.385277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,60대 이상,O,discount,131,112,88,67,7,31,0.854962,0.511450,0.598214,0.079545,0.276786
50,60대 이상,O,informational,71,56,0,0,0,56,0.788732,0.000000,0.000000,NaN,1.000000
51,누락,Unknown,bogo,3962,3385,401,260,69,3053,0.854366,0.065623,0.076809,0.172070,0.901920
52,누락,Unknown,discount,3879,2977,700,629,47,2324,0.767466,0.162155,0.211287,0.067143,0.780652
53,누락,Unknown,informational,1935,1362,0,0,0,1362,0.703876,0.000000,0.000000,NaN,1.000000

In [36]:
# -----------------------------------
# 5) 연령대 + 성별 조합별 최적 오퍼 1개 뽑기
#    기준: viewed 기준 정상 전환율
# -----------------------------------

best_offer_by_age_gender = (
    age_gender_offer_seg
    .sort_values(
        ['age_group', 'gender', 'valid_conversion_rate_per_viewed'],
        ascending=[True, True, False]
    )
    .groupby(['age_group', 'gender'], as_index=False)
    .first()
)

best_offer_by_age_gender[
    [
        'age_group', 'gender', 'offer_type',
        'n', 'view_rate',
        'valid_conversion_rate_per_received',
        'valid_conversion_rate_per_viewed',
        'completed_without_view_ratio',
        'dropout_after_view_ratio'
    ]
]

,age_group,gender,offer_type,n,view_rate,valid_conversion_rate_per_received,valid_conversion_rate_per_viewed,completed_without_view_ratio,dropout_after_view_ratio
0,20대,F,discount,701,0.631954,0.356633,0.564334,0.256466,0.221219
1,20대,M,discount,1816,0.575991,0.294053,0.510516,0.221550,0.385277
2,20대,O,discount,30,0.500000,0.233333,0.466667,0.181818,0.400000
3,20대 미만,F,discount,71,0.535211,0.211268,0.394737,0.333333,0.368421
4,20대 미만,M,discount,270,0.614815,0.348148,0.566265,0.201439,0.331325
5,30대,F,discount,891,0.663300,0.408530,0.615905,0.215559,0.181049
6,30대,M,discount,1874,0.636073,0.350053,0.550336,0.175026,0.323826
7,30대,O,discount,40,0.700000,0.450000,0.642857,0.185185,0.214286
8,40대,F,discount,1484,0.764825,0.453504,0.592952,0.152195,0.234361
9,40대,M,discount,2505,0.705389,0.390818,0.554046,0.148305,0.317487
10,40대,O,discount,68,0.823529,0.558824,0.678571,0.134615,0.196429
11,50대,F,discount,2827,0.697559,0.423771,0.607505,0.236425,0.194219
12,50대,M,discount,3445,0.698984,0.391582,0.560216,0.180897,0.294850
13,50대,O,bogo,86,0.918605,0.500000,0.544304,0.066667,0.291139
14,60대 이상,F,discount,4969,0.708593,0.421614,0.595001,0.225275,0.199091
15,60대 이상,M,discount,5444,0.701139,0.390889,0.557506,0.189028,0.287398
16,60대 이상,O,discount,131,0.854962,0.511450,0.598214,0.079545,0.276786
17,누락,Unknown,discount,3879,0.767466,0.162155,0.211287,0.067143,0.780652

In [37]:
df.shape

(76277, 38)