In [15]:
import pandas as pd
import numpy as np
import matplotlib
import ast
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings('ignore')

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

#폰트 설정(없으면 영문으로 나옴)
try:
    font_path = [f for f in fm.findSystemFonts() if 'NanumGothic' in f or 'Malgun' in f or 'AppleGothic' in f]
    if font_path:
        plt.rcParams['font.family'] = fm.FontProperties(fname=font_path[0]).get_name()
    else:
        plt.rcParams['font.family'] = 'DejaVu Sans'
except:
    plt.rcParams['font.family'] = 'DejaVu Sans'

plt.rcParams['axes.unicode_minus'] = False

In [16]:
df = pd.read_csv('./funnel_instance_analysis.csv')

In [17]:
df.shape

(76277, 34)

In [18]:
df.head()

,customer_id,offer_id,t_received,offer_type,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,gap_view_to_complete,is_viewed,is_completed,completed_without_view,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,gender,age_group,income_group,join_year,join_month,join_cohort
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,576,discount,1,7.0,744.0,NaN,NaN,NaN,NaN,576.0,576.0,1.0,0.0,NaN,0.0,NaN,False,True,True,2.0,10.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,336,informational,1,4.0,432.0,372.0,372.0,1.0,0.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,True,False,False,0.0,0.0,1.0,1.0,1.0,0.0,3.0,M,30대,5-7.5만,2017,4,2017-04
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,168,informational,1,3.0,240.0,192.0,192.0,1.0,0.0,NaN,NaN,NaN,NaN,24.0,NaN,NaN,True,False,False,0.0,0.0,0.0,1.0,1.0,1.0,3.0,M,30대,5-7.5만,2017,4,2017-04
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,408,bogo,1,5.0,528.0,456.0,456.0,1.0,0.0,414.0,414.0,1.0,0.0,48.0,6.0,NaN,True,True,True,5.0,5.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,504,discount,1,10.0,744.0,540.0,540.0,1.0,0.0,528.0,528.0,1.0,0.0,36.0,24.0,NaN,True,True,True,2.0,10.0,1.0,1.0,1.0,1.0,4.0,M,30대,5-7.5만,2017,4,2017-04

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76277 entries, 0 to 76276
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             76277 non-null  str
 1   offer_id                76277 non-null  str
 2   t_received              76277 non-null  int64
 3   offer_type              76277 non-null  str
 4   instance_id             76277 non-null  int64
 5   duration                76277 non-null  float64
 6   t_expire                76277 non-null  float64
 7   t_viewed                56567 non-null  float64
 8   last_viewed             56567 non-null  float64
 9   view_count              56567 non-null  float64
 10  view_ambiguous          56567 non-null  float64
 11  t_completed             33101 non-null  float64
 12  last_completed          33101 non-null  float64
 13  complete_count          33101 non-null  float64
 14  comp_ambiguous          33101 non-null  float64
 15  gap_to_view             56567 non-null  float64
 16  gap_to_complete         33101 non-null  float64
 17  gap_view_to_complete    23267 non-null  float64
 18  is_viewed               76277 non-null  bool
 19  is_completed            76277 non-null  bool
 20  completed_without_view  76277 non-null  bool
 21  reward                  76277 non-null  float64
 22  difficulty              76277 non-null  float64
 23  ch_web                  76277 non-null  float64
 24  ch_email                76277 non-null  float64
 25  ch_mobile               76277 non-null  float64
 26  ch_social               76277 non-null  float64
 27  channel_count           76277 non-null  float64
 28  gender                  76277 non-null  str
 29  age_group               76277 non-null  str
 30  income_group            76277 non-null  str
 31  join_year               76277 non-null  int64
 32  join_month              76277 non-null  int64
 33  join_cohort             76277 non-null  str
dtypes: bool(3), float64(20), int64(4), str(7)
memory usage: 18.3 MB

In [20]:
df.describe()

,t_received,instance_id,duration,t_expire,t_viewed,last_viewed,view_count,view_ambiguous,t_completed,last_completed,complete_count,comp_ambiguous,gap_to_view,gap_to_complete,gap_view_to_complete,reward,difficulty,ch_web,ch_email,ch_mobile,ch_social,channel_count,join_year,join_month
count,76277.000000,76277.000000,76277.000000,76277.000000,56567.000000,56567.000000,56567.0,56567.000000,33101.000000,33101.000000,33101.000000,33101.000000,56567.000000,33101.000000,23267.000000,76277.000000,76277.000000,76277.000000,76277.0,76277.000000,76277.000000,76277.000000,76277.000000,76277.000000
mean,332.579519,1.188012,6.503704,488.668406,353.750314,353.750314,1.0,0.041349,399.275430,399.413915,1.014441,0.040120,24.365620,61.174949,45.060730,4.201607,7.707723,0.799730,1.0,0.899472,0.598909,3.298111,2016.636522,6.678920
std,196.489548,0.436315,2.201544,203.330265,199.139007,199.139007,0.0,0.199098,192.748223,192.831514,0.119553,0.196243,28.453521,50.622756,43.383408,3.398888,5.538203,0.400205,0.0,0.300705,0.490123,0.640549,1.178704,3.489456
min,0.000000,1.000000,3.000000,72.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,2.000000,2013.000000,1.000000
25%,168.000000,1.000000,5.000000,336.000000,180.000000,180.000000,1.0,0.000000,234.000000,234.000000,1.000000,0.000000,6.000000,18.000000,12.000000,2.000000,5.000000,1.000000,1.0,1.000000,0.000000,3.000000,2016.000000,4.000000
50%,408.000000,1.000000,7.000000,528.000000,408.000000,408.000000,1.0,0.000000,432.000000,432.000000,1.000000,0.000000,12.000000,48.000000,30.000000,5.000000,10.000000,1.000000,1.0,1.000000,1.000000,3.000000,2017.000000,7.000000
75%,504.000000,1.000000,7.000000,672.000000,516.000000,516.000000,1.0,0.000000,558.000000,558.000000,1.000000,0.000000,36.000000,90.000000,66.000000,5.000000,10.000000,1.000000,1.0,1.000000,1.000000,4.000000,2017.000000,10.000000
max,576.000000,5.000000,10.000000,816.000000,714.000000,714.000000,1.0,1.000000,714.000000,714.000000,3.000000,1.000000,240.000000,240.000000,240.000000,10.000000,20.000000,1.000000,1.0,1.000000,1.000000,4.000000,2018.000000,12.000000

In [21]:
df.columns

Index(['customer_id', 'offer_id', 't_received', 'offer_type', 'instance_id',
       'duration', 't_expire', 't_viewed', 'last_viewed', 'view_count',
       'view_ambiguous', 't_completed', 'last_completed', 'complete_count',
       'comp_ambiguous', 'gap_to_view', 'gap_to_complete',
       'gap_view_to_complete', 'is_viewed', 'is_completed',
       'completed_without_view', 'reward', 'difficulty', 'ch_web', 'ch_email',
       'ch_mobile', 'ch_social', 'channel_count', 'gender', 'age_group',
       'income_group', 'join_year', 'join_month', 'join_cohort'],
      dtype='str')

In [22]:
seg = (
    df.groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed_rate=('is_viewed', 'mean'),
        completed_rate=('is_completed', 'mean')
    ).reset_index()
)

seg.head()

  gender age_group income_group    n  viewed_rate  completed_rate
0      F       20대       5-7.5만  973     0.683453        0.540596
1      F       20대        5만 미만  806     0.699752        0.468983
2      F       20대      7.5-10만   14     0.785714        0.857143
3      F    20대 미만       5-7.5만  127     0.669291        0.448819
4      F    20대 미만        5만 미만   76     0.750000        0.342105

In [23]:
seg_sorted = seg.sort_values('completed_rate', ascending=False)
seg_sorted.head(10)

   gender age_group income_group    n  viewed_rate  completed_rate
5       F       30대       10만 이상    4     1.000000        1.000000
2       F       20대      7.5-10만   14     0.785714        0.857143
26      M       30대       10만 이상    4     1.000000        0.750000
44      O       30대       5-7.5만   39     0.769231        0.717949
57      O    60대 이상      7.5-10만   73     1.000000        0.671233
51      O       50대       10만 이상    3     1.000000        0.666667
8       F       30대      7.5-10만  208     0.947115        0.658654
50      O       40대      7.5-10만   65     0.938462        0.646154
52      O       50대       5-7.5만   90     0.911111        0.644444
38      M    60대 이상       10만 이상  929     0.630786        0.635091

In [24]:
seg_filtered = seg[seg['n']>=100]
seg_filtered.sort_values('completed_rate', ascending=False).head(10)

   gender age_group income_group     n  viewed_rate  completed_rate
8       F       30대      7.5-10만   208     0.947115        0.658654
38      M    60대 이상       10만 이상   929     0.630786        0.635091
13      F       50대       10만 이상  1113     0.640611        0.619048
17      F    60대 이상       10만 이상  2039     0.648847        0.608632
20      F    60대 이상      7.5-10만  4577     0.721870        0.605418
9       F       40대       10만 이상   158     0.715190        0.601266
16      F       50대      7.5-10만  2738     0.735208        0.601169
34      M       50대       10만 이상   588     0.637755        0.598639
12      F       40대      7.5-10만   889     0.870641        0.592801
41      M    60대 이상      7.5-10만  3320     0.790361        0.588855

# complete_given_view를 보는 이유
# - 단순 completed_rate는 '받은 전체 오퍼 중 완료 비율'이므로,
#   오퍼를 실제로 본 뒤 행동한 것인지까지는 구분하지 못한다.
# - 이번 분석에서는 퍼널 구조(received → viewed → completed)를 반영해,
#   '오퍼를 본 사람들 중 실제 완료로 이어진 비율'을 따로 확인하고자 한다.
# - 이를 통해
#   1) 오퍼를 봤을 때 구매로 잘 이어지는 고객층
#   2) 오퍼를 보지 않았는데도 완료되는 고객층
#   을 구분해 해석할 수 있다.
# - 전자는 어떤 오퍼가 효과적인지 추가 분석 대상으로,
#   후자는 프로모션 효율 재검토 대상으로 볼 수 있다.

In [25]:
seg = (
    df
    .groupby(['gender', 'age_group', 'income_group'])
    .agg(
        n=('customer_id', 'count'),
        viewed_rate=('is_viewed', 'mean'),
        completed_rate=('is_completed', 'mean'),
        completed_without_view_rate=('completed_without_view', 'mean')
    )
    .reset_index()
)

seg['complete_given_view'] = np.where(
    seg['viewed_rate'] > 0,
    seg['completed_rate'] / seg['viewed_rate'],
    np.nan
)

seg.head()

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
1,F,20대,5만 미만,806,0.699752,0.468983,0.162531,0.670213
2,F,20대,7.5-10만,14,0.785714,0.857143,0.428571,1.090909
3,F,20대 미만,5-7.5만,127,0.669291,0.448819,0.196850,0.670588
4,F,20대 미만,5만 미만,76,0.750000,0.342105,0.144737,0.456140

In [26]:
seg[seg['n'] >= 100].sort_values('complete_given_view', ascending=False).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
38,M,60대 이상,10만 이상,929,0.630786,0.635091,0.258342,1.006826
13,F,50대,10만 이상,1113,0.640611,0.619048,0.242588,0.966339
34,M,50대,10만 이상,588,0.637755,0.598639,0.241497,0.938667
17,F,60대 이상,10만 이상,2039,0.648847,0.608632,0.243747,0.938020
9,F,40대,10만 이상,158,0.715190,0.601266,0.196203,0.840708
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
6,F,30대,5-7.5만,1140,0.722807,0.552632,0.192105,0.764563
41,M,60대 이상,7.5-10만,3320,0.790361,0.588855,0.180422,0.745046

In [27]:
seg[seg['n'] >= 100].sort_values('completed_without_view_rate', ascending=False).head(10)

,gender,age_group,income_group,n,viewed_rate,completed_rate,completed_without_view_rate,complete_given_view
38,M,60대 이상,10만 이상,929,0.630786,0.635091,0.258342,1.006826
17,F,60대 이상,10만 이상,2039,0.648847,0.608632,0.243747,0.938020
13,F,50대,10만 이상,1113,0.640611,0.619048,0.242588,0.966339
34,M,50대,10만 이상,588,0.637755,0.598639,0.241497,0.938667
0,F,20대,5-7.5만,973,0.683453,0.540596,0.210689,0.790977
20,F,60대 이상,7.5-10만,4577,0.721870,0.605418,0.203845,0.838680
16,F,50대,7.5-10만,2738,0.735208,0.601169,0.201972,0.817685
3,F,20대 미만,5-7.5만,127,0.669291,0.448819,0.196850,0.670588
9,F,40대,10만 이상,158,0.715190,0.601266,0.196203,0.840708
6,F,30대,5-7.5만,1140,0.722807,0.552632,0.192105,0.764563

In [ ]:
seg['segment_share'] = seg['n'] / seg['n'].sum()
seg.head()